export const premium = [
  {
    line: "Premium",
    code: "140p-a",
    imgAlt: "maqueta de la casa 140 premium a",
    price: "240.800",
    size: "140",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "75",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "140p-b",
    imgAlt: "maqueta de la casa 140 premium b",
    price: "252.000",
    size: "140",
    bedrooms: "3",
    bathrooms: "2",
    roof: "a aguas",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "75",
    cover: "15cm con teja asfáltica.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-a",
    imgAlt: "maqueta de la casa 150 premium a",
    price: "262.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "a aguas",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm con teja asfáltica.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-b",
    imgAlt: "maqueta de la casa 150 premium b",
    price: "253.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-c",
    imgAlt: "maqueta de la casa 150 premium c",
    price: "262.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "a aguas",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm con teja asfáltica.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-d",
    imgAlt: "maqueta de la casa 150 premium d",
    price: "253.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-e",
    imgAlt: "maqueta de la casa 150 premium e",
    price: "262.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "a aguas",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm con teja asfáltica.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-f",
    imgAlt: "maqueta de la casa 150 premium f",
    price: "253.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-g",
    imgAlt: "maqueta de la casa 150 premium g",
    price: "262.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "a aguas",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm con teja asfáltica.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-h",
    imgAlt: "maqueta de la casa 150 premium h",
    price: "253.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "150p-i",
    imgAlt: "maqueta de la casa 150 premium i",
    price: "253.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "80",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "163p-a",
    imgAlt: "maqueta de la casa 163 premium a",
    price: "275.470",
    size: "163",
    bedrooms: "4",
    bathrooms: "2",
    roof: "plano",
    description:
      "4 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "90",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "178p-a",
    imgAlt: "maqueta de la casa 178 premium a",
    price: "300.820",
    size: "178",
    bedrooms: "4",
    bathrooms: "3",
    roof: "plano",
    description:
      "4 dormitorios, 3 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "95",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "235p-a",
    imgAlt: "maqueta de la casa 235 premium a",
    price: "411.250",
    size: "235",
    bedrooms: "3",
    bathrooms: "2",
    roof: "a aguas",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero. ",
    estimated: "100",
    cover: "15cm con teja asfáltica.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Premium",
    code: "285p-a",
    imgAlt: "maqueta de la casa 285 premium a",
    price: "481.650",
    size: "285",
    bedrooms: "5",
    bathrooms: "4",
    roof: "plano",
    description:
      "5 dormitorios, 4 baños completos (1 baño social), living/cocina/comedor, lavadero y garage.",
    estimated: "120",
    cover: "15cm.",
    paint: "lavable",
    serie: "Gala con DVH",
    counter: "Mesadas de cocina y baños",
  },
];

export const executivePlus = [
  {
    line: "Ejecutiva Plus",
    code: "115ep-a",
    imgAlt: "maqueta de la casa 115 ejecutiva plus a",
    price: "181.125",
    size: "115",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "60",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "120ep-a",
    imgAlt: "maqueta de la casa 120 ejecutiva plus a",
    price: "189.000",
    size: "120",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "70",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "135ep-a",
    imgAlt: "maqueta de la casa 135 ejecutiva plus a",
    price: "209.250",
    size: "135",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "70",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "140ep-a",
    imgAlt: "maqueta de la casa 140 ejecutiva plus a",
    price: "217.000",
    size: "140",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "75",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "145ep-a",
    imgAlt: "maqueta de la casa 145 ejecutiva plus a",
    price: "224.750",
    size: "145",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "75",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "150ep-a",
    imgAlt: "maqueta de la casa 150 ejecutiva plus a",
    price: "232.500",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "80",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "150ep-b",
    imgAlt: "maqueta de la casa 150 ejecutiva plus b",
    price: "285.700",
    size: "150",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "80",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
    extras: "Este proyecto incluye 54m² de cochera cubierta y depósito.",
  },
  {
    line: "Ejecutiva Plus",
    code: "160ep-a",
    imgAlt: "maqueta de la casa 160 ejecutiva plus a",
    price: "248.000",
    size: "160",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "85",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva Plus",
    code: "165ep-a",
    imgAlt: "maqueta de la casa 165 ejecutiva plus a",
    price: "255.750",
    size: "165",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor, lavadero y barbacoa cerrada.",
    estimated: "90",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con DVH",
    counter: "Mesadas de cocina y baños",
  },
];

export const executive = [
  {
    line: "Ejecutiva",
    code: "70e-a",
    imgAlt: "maqueta de la casa 70 ejecutiva a",
    price: "103.950",
    size: "70",
    bedrooms: "2",
    bathrooms: "1",
    roof: "plano",
    description: "2 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "50",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "70e-b",
    imgAlt: "maqueta de la casa 70 ejecutiva b",
    price: "103.950",
    size: "70",
    bedrooms: "2",
    bathrooms: "2",
    roof: "plano",
    description: "2 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "50",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "75e-a",
    imgAlt: "maqueta de la casa 75 ejecutiva a",
    price: "113.375",
    size: "75",
    bedrooms: "3",
    bathrooms: "1",
    roof: "plano",
    description: "3 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "50",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "90e-a",
    imgAlt: "maqueta de la casa 90 ejecutiva a",
    price: "133.650",
    size: "90",
    bedrooms: "2",
    bathrooms: "2",
    roof: "plano",
    description: "2 dormitorios, 2 baños completos y living/cocina/comedor.",
    estimated: "55",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "100e-a",
    imgAlt: "maqueta de la casa 100 ejecutiva a",
    price: "148.500",
    size: "100",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description: "3 dormitorios, 2 baños completos y living/cocina/comedor.",
    estimated: "60",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "115e-a",
    imgAlt: "maqueta de la casa 115 ejecutiva a",
    price: "170.775",
    size: "115",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description: "3 dormitorios, 2 baños completos y living/cocina/comedor.",
    estimated: "60",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "120e-a",
    imgAlt: "maqueta de la casa 120 ejecutiva a",
    price: "178.200",
    size: "120",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "70",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "135e-a",
    imgAlt: "maqueta de la casa 135 ejecutiva a",
    price: "200.475",
    size: "135",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos, living/cocina/comedor y lavadero.",
    estimated: "70",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
  {
    line: "Ejecutiva",
    code: "140e-a",
    imgAlt: "maqueta de la casa 140 ejecutiva a",
    price: "207.900",
    size: "140",
    bedrooms: "3",
    bathrooms: "2",
    roof: "plano",
    description:
      "3 dormitorios, 2 baños completos (1 baño social), living/cocina/comedor y lavadero.",
    estimated: "75",
    cover: "15cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesadas de cocina y baños",
  },
];
export const basic = [
  {
    line: "Básica",
    code: "35b-a",
    imgAlt: "maqueta de la casa 35 basic a",
    price: "49.875",
    size: "35",
    bedrooms: "1",
    bathrooms: "1",
    roof: "plano",
    description: "1 dormitorio, 1 baño completo y living/cocina/comedor.",
    estimated: "30",
    cover: "10cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesada de cocina",
  },
  {
    line: "Básica",
    code: "45b-a",
    imgAlt: "maqueta de la casa 45 basic a",
    price: "64.125",
    size: "45",
    bedrooms: "2",
    bathrooms: "1",
    roof: "plano",
    description: "2 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "40",
    cover: "10cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesada de cocina",
  },
  {
    line: "Básica",
    code: "55b-a",
    imgAlt: "maqueta de la casa 55 basic a",
    price: "78.375",
    size: "55",
    bedrooms: "2",
    bathrooms: "1",
    roof: "plano",
    description: "2 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "45",
    cover: "10cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesada de cocina",
  },
  {
    line: "Básica",
    code: "60b-a",
    imgAlt: "maqueta de la casa 60 basic a",
    price: "85.500",
    size: "60",
    bedrooms: "2",
    bathrooms: "1",
    roof: "plano",
    description: "2 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "50",
    cover: "10cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesada de cocina",
  },
  {
    line: "Básica",
    code: "70b-a",
    imgAlt: "maqueta de la casa 70 basic a",
    price: "99.750",
    size: "70",
    bedrooms: "2",
    bathrooms: "1",
    roof: "plano",
    description: "2 dormitorios, 1 baño completo y living/cocina/comedor.",
    estimated: "50",
    cover: "10cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesada de cocina",
  },
  {
    line: "Básica",
    code: "70b-b",
    imgAlt: "maqueta de la casa 70 basic b",
    price: "99.750",
    size: "70",
    bedrooms: "2",
    bathrooms: "2",
    roof: "plano",
    description: "2 dormitorios, 2 baños completos y living/cocina/comedor.",
    estimated: "50",
    cover: "10cm.",
    paint: "color blanco",
    serie: "Probba con vidrio simple",
    counter: "Mesada de cocina",
  },
];

export const allProducts = [
  ...premium,
  ...executivePlus,
  ...executive,
  ...basic,
];
